### PR TITLE
Newfeature

### PR DESCRIPTION
**Pull request by Ranjeetmdl**
Hi Mandal,

Please review and approve the codes.

Thanks,
Ranjeet

### CODE REVIEW

**Review by jeet1504 — CHANGES_REQUESTED** [review]
Hi R,

Please add variable x & y in th sop, rest all looks good

Thanks,
M

**Review by jeet1504 — APPROVED** [review]
Hi R,

you can merge ,ur code looks great.

Thanks,
M

**Comment by Ranjeetmdl** [comment]
merging new features in the master branch.

**Comment by Ranjeetmdl** [comment]
merging features in the master

**Pull request merged**
